module.exports = {
  // France
  'Paris Saint-Germain FC': 'Paris Saint Germain',
  'FC Nantes': 'Nantes',
  'Stade Brestois 29': 'Brest',
  'Racing Club de Lens': 'RC Lens',
  'Angers SCO': 'Angers',
  'FC Lorient': 'Lorient',
  'Stade de Reims': 'Stade de Reims',
  'Clermont Foot 63': 'Clermont',
  'Lille OSC': 'Lille',
  'Olympique de Marseille': 'Marseille',
  'AS Monaco FC': 'AS Monaco',
  'Olympique Lyonnais': 'Lyon',
  'ES Troyes AC': 'Troyes',
  'Stade Rennais FC 1901': 'Rennes',
  'RC Strasbourg Alsace': 'Strasbourg',
  'AS Saint-Étienne': 'Saint Etienne',
  'OGC Nice': 'Nice',
  'FC Girondins de Bordeaux': 'Bordeaux',
  'FC Metz': 'Metz',
  'Montpellier HSC': 'Montpellier',
  // Allemagne
  '1. FC Köln': 'FC Koln',
  'VfL Bochum 1848': 'VfL Bochum',
  'Arminia Bielefeld': 'Arminia Bielefeld',
  'Eintracht Frankfurt': 'Eintracht Frankfurt',
  'FC Augsburg': 'Augsburg',
  'Bayer 04 Leverkusen': 'Bayer Leverkusen', 
  '1. FSV Mainz 05': 'FSV Mainz 05',
  'SpVgg Greuther Fürth 1903': 'Greuther Fürth',
  'VfB Stuttgart': 'VfB Stuttgart',
  'SC Freiburg': 'SC Freiburg',
  'FC Bayern München': 'Bayern Munich',
  'Hertha BSC': 'Hertha Berlin', 
  '1. FC Union Berlin': 'Union Berlin',
  'Borussia Mönchengladbach': 'Borussia Monchengladbach',
  'VfL Wolfsburg': 'VfL Wolfsburg',
  'RB Leipzig': 'RB Leipzig',
  'Borussia Dortmund': 'Borussia Dortmund',
  'TSG 1899 Hoffenheim': 'TSG Hoffenheim',
  // Angleterre
  'Crystal Palace FC': 'Crystal Palace',
  'Tottenham Hotspur FC': 'Tottenham Hotspur',
  'Arsenal FC': 'Arsenal',
  'Norwich City FC': 'Norwich City',
  'Brentford FC': 'Brentford',
  'Brighton & Hove Albion FC': 'Brighton and Hove Albion',
  'Leicester City FC': 'Leicester City',
  'Manchester City FC': 'Manchester City',
  'Manchester United FC': 'Manchester United',
  'Newcastle United FC': 'Newcastle United',
  'Southampton FC': 'Southampton',
  'West Ham United FC': 'West Ham United',
  'Watford FC': 'Watford',
  'Wolverhampton Wanderers FC': 'Wolverhampton Wanderers',
  'Chelsea FC': 'Chelsea',
  'Aston Villa FC': 'Aston Villa',
  'Leeds United FC': 'Leeds United',
  'Liverpool FC': 'Liverpool',
  'Everton FC': 'Everton',
  'Burnley FC': 'Burnley',
  // Italie
  'Empoli FC': 'Empoli',
  'Venezia FC': 'Venezia',
  'SSC Napoli': 'Napoli',
  'Juventus FC': 'Juventus',
  'Atalanta BC': 'Atalanta BC',
  'ACF Fiorentina': 'Fiorentina',
  'UC Sampdoria': 'Sampdoria',
  'FC Internazionale Milano': 'Inter Milan',
  'Cagliari Calcio': 'Cagliari',
  'Genoa CFC': 'Genoa',
  'Spezia Calcio': 'Spezia',
  'Udinese Calcio': 'Udinese',
  'Torino FC': 'Torino',
  'US Salernitana 1919': 'Salernitana',
  'AC Milan': 'AC Milan',
  'SS Lazio': 'Lazio',
  'AS Roma': 'AS Roma',
  'US Sassuolo Calcio': 'Sassuolo',
  'Bologna FC 1909': 'Bologna',
  'Hellas Verona FC': 'Hellas Verona FC',
  // Espagne
  'Villarreal CF': 'Villarreal',
  'Deportivo Alavés': 'Alavés',
  'Levante UD': 'Levante',
  'Rayo Vallecano de Madrid': 'Rayo Vallecano',
  'Sevilla FC': 'Sevilla',
  'FC Barcelona': 'Barcelona',
  'Athletic Club': 'Athletic Bilbao',
  'RCD Mallorca': 'Mallorca',
  'RCD Espanyol de Barcelona': 'Espanyol',
  'Club Atlético de Madrid': 'Atlético Madrid',
  'CA Osasuna': 'CA Osasuna',
  'Valencia CF': 'Valencia',
  'Cádiz CF': 'Cádiz CF',
  'Real Sociedad de Fútbol': 'Real Sociedad',
  'Real Madrid CF': 'Real Madrid',
  'RC Celta de Vigo': 'Celta Vigo',
  'Getafe CF': 'Getafe',
  'Elche CF': 'Elche CF',
  'Granada CF': 'Granada CF',
  'Real Betis Balompié': 'Real Betis',
  // Pays-Bas
  'Fortuna Sittard': 'Fortuna Sittard',
  'Ajax': 'AFC Ajax',
  'RKC Waalwijk': 'RKC Waalwijk',
  'Willem II': 'Willem II Tilburg',
  'NEC Nijmegen': 'NEC Nijmegen',
  'FC Utrecht': 'FC Utrecht',
  'Go Ahead Eagles': 'Go Ahead Eagles',
  'PSV Eindhoven': 'PSV',
  'Groningen': 'FC Groningen',
  'Vitesse Arnhem': 'SBV Vitesse',
  'FC Zwolle': 'FC Zwolle',
  'Sparta Rotterdam': 'Sparta Rotterdam',
  'Feyenoord': 'Feyenoord Rotterdam',
  'Heerenveen': 'SC Heerenveen',
  'SC Cambuur': 'SC Cambuur-Leeuwarden',
  'Heracles Almelo': 'Heracles Almelo',
  'FC Twente Enschede': "FC Twente '65",
  'AZ Alkmaar': 'AZ',
  // Portugal
  'Estoril': 'GD Estoril Praia',
  'Sporting Lisbon': 'Sporting Clube de Portugal',
  'Benfica': 'Sport Lisboa e Benfica',
  'Boavista Porto': 'Boavista FC',
  'Braga': 'Sporting Clube de Braga',
  'Tondela': 'CD Tondela',
  'CS Maritimo': 'CS Marítimo',
  'Gil Vicente': 'Gil Vicente FC',
  'FC Porto': 'FC Porto',
  'Moreirense FC': 'Moreirense FC',
  'Arouca': 'FC Arouca',
  'Vitória SC': 'Vitória SC',
  'Famalicão': 'FC Famalicão',
  'Santa Clara': 'CD Santa Clara',
  'Portimonense': 'Portimonense SC',
  'Vizela': 'FC Vizela',
  'Pacos de Ferreira': 'FC Paços de Ferreira',
  'Belenenses': 'Os Belenenses Futebol',
}
