module.exports = {
  // France
  'AC Ajaccio': 'AC Ajaccio',
  'AJ Auxerre': 'Auxerre',
  'Angers SCO': 'Angers',
  'AS Monaco FC': 'AS Monaco',
  'AS Saint-Étienne': 'Saint Etienne',
  'Clermont Foot 63': 'Clermont',
  'ES Troyes AC': 'Troyes',
  'FC Girondins de Bordeaux': 'Bordeaux',
  'FC Lorient': 'Lorient',
  'FC Metz': 'Metz',
  'FC Nantes': 'Nantes',
  'Le Havre AC': 'Le Havre',
  'Lille OSC': 'Lille',
  'Montpellier HSC': 'Montpellier',
  'OGC Nice': 'Nice',
  'Olympique de Marseille': 'Marseille',
  'Olympique Lyonnais': 'Lyon',
  'Paris Saint-Germain FC': 'Paris Saint Germain',
  'Racing Club de Lens': 'RC Lens',
  'RC Strasbourg Alsace': 'Strasbourg',
  'Stade Brestois 29': 'Brest',
  'Stade de Reims': 'Stade de Reims',
  'Stade Rennais FC 1901': 'Rennes',
  'Toulouse FC': 'Toulouse',
  // Allemagne
  '1. FC Heidenheim 1846': 'FC Heidenheim',
  '1. FC Köln': 'FC Koln',
  '1. FC Union Berlin': 'Union Berlin',
  '1. FSV Mainz 05': 'FSV Mainz 05',
  'Arminia Bielefeld': 'Arminia Bielefeld',
  'Bayer 04 Leverkusen': 'Bayer Leverkusen',
  'Borussia Dortmund': 'Borussia Dortmund',
  'Borussia Mönchengladbach': 'Borussia Monchengladbach',
  'Eintracht Frankfurt': 'Eintracht Frankfurt',
  'FC Augsburg': 'Augsburg',
  'FC Bayern München': 'Bayern Munich',
  'FC Schalke 04': 'Schalke 04',
  'Hertha BSC': 'Hertha Berlin',
  'RB Leipzig': 'RB Leipzig',
  'SC Freiburg': 'SC Freiburg',
  'SpVgg Greuther Fürth 1903': 'Greuther Fürth',
  'SV Darmstadt 98': 'SV Darmstadt 98',
  'SV Werder Bremen': 'Werder Bremen',
  'TSG 1899 Hoffenheim': 'TSG Hoffenheim',
  'VfB Stuttgart': 'VfB Stuttgart',
  'VfL Bochum 1848': 'VfL Bochum',
  'VfL Wolfsburg': 'VfL Wolfsburg',
  // Angleterre
  'AFC Bournemouth': 'Bournemouth',
  'Arsenal FC': 'Arsenal',
  'Aston Villa FC': 'Aston Villa',
  'Brentford FC': 'Brentford',
  'Brighton & Hove Albion FC': 'Brighton and Hove Albion',
  'Burnley FC': 'Burnley',
  'Chelsea FC': 'Chelsea',
  'Crystal Palace FC': 'Crystal Palace',
  'Everton FC': 'Everton',
  'Fulham FC': 'Fulham',
  'Leeds United FC': 'Leeds United',
  'Leicester City FC': 'Leicester City',
  'Liverpool FC': 'Liverpool',
  'Luton Town FC': 'Luton',
  'Manchester City FC': 'Manchester City',
  'Manchester United FC': 'Manchester United',
  'Newcastle United FC': 'Newcastle United',
  'Norwich City FC': 'Norwich City',
  'Nottingham Forest FC': 'Nottingham Forest',
  'Sheffield United FC': 'Sheffield United',
  'Southampton FC': 'Southampton',
  'Tottenham Hotspur FC': 'Tottenham Hotspur',
  'Watford FC': 'Watford',
  'West Ham United FC': 'West Ham United',
  'Wolverhampton Wanderers FC': 'Wolverhampton Wanderers',
  // Italie
  'AC Milan': 'AC Milan',
  'AC Monza': 'Monza',
  'ACF Fiorentina': 'Fiorentina',
  'AS Roma': 'AS Roma',
  'Atalanta BC': 'Atalanta BC',
  'Bologna FC 1909': 'Bologna',
  'Cagliari Calcio': 'Cagliari',
  'Empoli FC': 'Empoli',
  'FC Internazionale Milano': 'Inter Milan',
  'Frosinone Calcio': 'Frosinone',
  'Genoa CFC': 'Genoa',
  'Hellas Verona FC': 'Hellas Verona FC',
  'Juventus FC': 'Juventus',
  'Spezia Calcio': 'Spezia',
  'SS Lazio': 'Lazio',
  'SSC Napoli': 'Napoli',
  'Torino FC': 'Torino',
  'UC Sampdoria': 'Sampdoria',
  'Udinese Calcio': 'Udinese',
  'US Cremonese': 'Cremonese',
  'US Lecce': 'Lecce',
  'US Salernitana 1919': 'Salernitana',
  'US Sassuolo Calcio': 'Sassuolo',
  'Venezia FC': 'Venezia',
  // Espagne
  'Athletic Club': 'Athletic Bilbao',
  'CA Osasuna': 'CA Osasuna',
  'Cádiz CF': 'Cádiz CF',
  'Club Atlético de Madrid': 'Atlético Madrid',
  'Deportivo Alavés': 'Alavés',
  'Elche CF': 'Elche CF',
  'FC Barcelona': 'Barcelona',
  'Getafe CF': 'Getafe',
  'Girona F': 'Girona',
  'Granada CF': 'Granada CF',
  'Levante UD': 'Levante',
  'Rayo Vallecano de Madrid': 'Rayo Vallecano',
  'RC Celta de Vigo': 'Celta Vigo',
  'RCD Espanyol de Barcelona': 'Espanyol',
  'RCD Mallorca': 'Mallorca',
  'Real Betis Balompié': 'Real Betis',
  'Real Madrid CF': 'Real Madrid',
  'Real Sociedad de Fútbol': 'Real Sociedad',
  'Real Valladolid CF': 'Valladolid',
  'Sevilla FC': 'Sevilla',
  'UD Almería': 'Almería',
  'UD Las Palmas': 'Las Palmas',
  'Valencia CF': 'Valencia',
  'Villarreal CF': 'Villarreal',
  // Pays-Bas
  'AFC Ajax': 'Ajax',
  'Almere City FC': 'Almere City',
  AZ: 'AZ Alkmaar',
  'FC Emmen': 'FC Emmen',
  'FC Groningen': 'Groningen',
  'FC Utrecht': 'FC Utrecht',
  'FC Volendam': 'FC Volendam',
  'Feyenoord Rotterdam': 'Feyenoord',
  'Fortuna Sittard': 'Fortuna Sittard',
  'Go Ahead Eagles': 'Go Ahead Eagles',
  'Heracles Almelo': 'Heracles Almelo',
  NEC: 'NEC Nijmegen',
  'PEC Zwolle': 'FC Zwolle',
  PSV: 'PSV Eindhoven',
  'RKC Waalwijk': 'RKC Waalwijk',
  'SBV Excelsior': 'Excelsior',
  'SBV Vitesse': 'Vitesse Arnhem',
  'SC Cambuur-Leeuwarden': 'SC Cambuur',
  'SC Heerenveen': 'Heerenveen',
  'Sparta Rotterdam': 'Sparta Rotterdam',
  'Willem II Tilburg': 'Willem II',
  "FC Twente '65": 'FC Twente Enschede',
  // Portugal
  'Boavista FC': 'Boavista Porto',
  'Casa Pia AC': 'Casa Pia',
  'CD Santa Clara': 'Santa Clara',
  'CF Estrela da Amadora': 'CF Estrela',
  'CD Tondela': 'Tondela',
  'CS Marítimo': 'CS Maritimo',
  'FC Arouca': 'Arouca',
  'FC Famalicão': 'Famalicão',
  'FC Paços de Ferreira': 'Pacos de Ferreira',
  'FC Porto': 'FC Porto',
  'FC Vizela': 'Vizela',
  'GD Chaves': 'Chaves',
  'GD Estoril Praia': 'Estoril',
  'Gil Vicente FC': 'Gil Vicente',
  'Moreirense FC': 'Moreirense FC',
  'Os Belenenses Futebol': 'Belenenses',
  'Portimonense SC': 'Portimonense',
  'Rio Ave FC': 'Rio Ave FC',
  'SC Farense': 'SC Farense',
  'Sport Lisboa e Benfica': 'Benfica',
  'Sporting Clube de Braga': 'Braga',
  'Sporting Clube de Portugal': 'Sporting Lisbon',
  'Vitória SC': 'Vitória SC',
};
